/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.ea2.fightingGame.frontEnd;

import javax.swing.*;

import dev.ea2.fightingGame.characters.Game;
import dev.ea2.fightingGame.frontEnd.mainMenu;

/**
 *
 * @author yeems214
 */
public class characterSelect1 extends javax.swing.JFrame {

    private mainMenu mainMenuInstance; // Add this line

    public characterSelect1(mainMenu mainMenuInstance) {
        this.mainMenuInstance = mainMenuInstance;
        initComponents();
    }

    @Override
    public void pack() {
        super.pack();
        setSize(1280, 720); // Set the size of the window here
    }

    /**
     * Creates new form aboutus
     */
    public characterSelect1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        officeProsecutors = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        officesWright = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        theCourtroom = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        officeProsecutors.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        officeProsecutors.setText("Edgey Office");
        officeProsecutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officeProsecutorsActionPerformed(evt);
            }
        });
        getContentPane().add(officeProsecutors);
        officeProsecutors.setBounds(950, 510, 190, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maps/thumbnails/edgeyOffice.jpg"))); // NOI18N
        jLabel6.setText("jLabel3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(870, 110, 360, 380);

        officesWright.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        officesWright.setText("Office");
        officesWright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officesWrightActionPerformed(evt);
            }
        });
        getContentPane().add(officesWright);
        officesWright.setBounds(540, 510, 190, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maps/thumbnails/office.jpg"))); // NOI18N
        jLabel5.setText("jLabel3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 110, 360, 380);

        theCourtroom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        theCourtroom.setText("Court");
        theCourtroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theCourtroomActionPerformed(evt);
            }
        });
        getContentPane().add(theCourtroom);
        theCourtroom.setBounds(150, 510, 190, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maps/thumbnails/court.jpg"))); // NOI18N
        jLabel4.setText("jLabel3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 110, 360, 380);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 360, 370);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select a Stage");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 40, 340, 60);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterSelect1.this.setVisible(false); // Hide the current window
                new mainMenu();
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 600, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/character-select.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false); // Hide the current window
        new mainMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void officeProsecutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officeProsecutorsActionPerformed
        characterSelect1.this.setVisible(false);
        String imageFile = "/images/maps/thumbnails/edgeyOffice.jpg";
        Game.gago(imageFile);
    }//GEN-LAST:event_officeProsecutorsActionPerformed

    private void officesWrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officesWrightActionPerformed
        characterSelect1.this.setVisible(false);
        String imageFile = "/images/maps/thumbnails/office.jpg";
        Game.gago(imageFile);
    }//GEN-LAST:event_officesWrightActionPerformed

    private void theCourtroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theCourtroomActionPerformed
        characterSelect1.this.setVisible(false);
        String imageFile = "/images/maps/thumbnails/court.jpg";
        Game.gago(imageFile);
    }//GEN-LAST:event_theCourtroomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(characterSelect1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(characterSelect1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(characterSelect1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(characterSelect1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new characterSelect1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton officeProsecutors;
    private javax.swing.JButton officesWright;
    private javax.swing.JButton theCourtroom;
    // End of variables declaration//GEN-END:variables
}
